### ISSUE TITLE
stuck at "waiting for whatsapp connection, please authorize whatsapp web"

### ISSUE THREAD

**Issue by bkmikaelo7** [iongpt/LLM-for-Whatsapp#10]
Hi,
I'm on mac os Sonoma. Electron just sits there waiting for the chromium to authorize whatsapp web.

getting this on terminal:
"
(openwebui) petriml@iMac-Pro LLM-for-Whatsapp % yarn run dev
yarn run v1.22.22
$ electron --inspect=5858 ./app
Debugger listening on ws://127.0.0.1:5858/542aa300-51f9-4e70-8f51-701e8b1c349b
For help, see: https://nodejs.org/en/docs/inspector
2024-11-01 21:49:24.332 Electron[65329:1943533] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
(node:65329) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/Users/petriml/LLM-for-Whatsapp/app/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /Users/petriml/LLM-for-Whatsapp/app/node_modules/whatsapp-web.js/src/Client.js:744:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:65329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2) "

Nothing happens after I've logged in to whatsapp web on Chromium window.

Should I allow some accessibility etc options in the "privacy and security" settings on mac os? Usually
os reports beforehand if app need accessibility options enabled for the app.

**Comment by RPHllc** [comment]
I have the same issue on mac, macOS Sequoia.  Chrome launches and I use the WhatsApp on my phone to authorize the web.whatsapp.com page, after that my chats load on the screen. The separate screen continues to say "Waiting for whatsApp connection, please authorize WhatsApp web".

**Comment by rohitmenonhart-xhunter** [comment]
got any fix?

**Comment by RPHllc** [comment]
I made progress updating some packages and using npm as follows:
1) deleted the package lock files from the root and the ./app directories.
2) updated electron package in package.json
3) used npm outdated and followed recommendation
2) run "npm i" on root and ./app directories
3) execute "npm run dev" from root directory.

The code now runs. After authorizing the web WhatsApp the code loads the contacts. I am able to pick myself as contact and post a "hi" in my name. I did not see any post from the LLM itself, but I do not know what I am supposed to do next.

I forked the code and uploaded the changes above. https://github.com/RPHllc/LLM-for-Whatsapp

**Comment by bkmikaelo7** [comment]
Perhaps try one of the newer forks. That's what I did and got it working, though I had to edit some code to get Ollama api working and get api query to trigger in whatsapp group chat setting.

edit: @RPHllc Great to hear you got it working.  Are you planning to use Oobabooga or Ollama as an LLM server? There was something in the API formatting I had to change for Ollama. I can check it out later if you need help.

**Comment by RPHllc** [comment]
@bkmikaelo7 : I am planning to use a local Ollama instance. For now I am using OpenAI just to reduce the number of variables, but please share the API formatting that you had to make.

Please also explain what I should have seen. This is what I see when I start the code from the fork I created:
1) the code retrieves contacts, 
2) I am able to search and retrieve my name,
3) I am able to post a "hi" using the green button, it posts "hi" impersonating me.
But nothing else happens. It seems that the LLM is not doing anything.

**Comment by bkmikaelo7** [comment]
@RPHllc You need at least two whatsapp numbers to test it, one for the LLM/frontend and one conversation partner. (The code references the user as "system" (if I recall right), so it doesn't forward messages to LLM from that iD/number.Then pick the name/identity you want to start conversation with from the table of contacts and press "start conversation". All should work in 1v1 conversations without modifications, but not in group chats. Check what the console logs tell you. It should say something like "using local LLM" if the message is picked up and forwarded to the LLM. If not, then it could be that the sender phone number doesn't match with the one added to the contacts table or such, which was the case with the group chat, why it was necessary to change the code to reference contacts by IDs rather than numbers (which is the default, i think). If the message is forwarded to the LLM but nothing happens, or you get some error, then I would guess the issue is with the settings or the API query formatting.

**Comment by alfi4000** [comment]
Linux X64 same issue!

**Comment by iongpt** [comment]
Sorry for late response, incredibly busy those days.

But I am in advanced discussions with a new developer to take over the project and the first task is to fix this issues. It should be fixed in the next few days.

Also there are plans for a headless mode

**Comment by iongpt** [comment]
Version 2 just dropped, the issue si fixed
